### ISSUE TITLE
Общие недочеты

### ISSUE THREAD

**Issue by mglknFSD** [igor-smolkov/toxin#29]
1. Странное поведение анимации для иконок социальных сетей - анимация не отжимается. Браузер Firefox. 

https://user-images.githubusercontent.com/75975369/145666450-60cacc2e-5c7e-4d80-9709-e3454eb8d4ae.mp4

2. У нас в бест практис есть пункт по поводу того куда должны вести ссылки на сторонние сервисы.

**Comment by mglknFSD** [comment]
3. Hover эффект в меню влияет на размер элемента и двигает соседей. Такого поведения лучше избегать

https://user-images.githubusercontent.com/75975369/145666531-d6bae25f-c094-4eb1-ae56-04afe172ba3d.mp4

.

**Comment by mglknFSD** [comment]
4. Футер 
 - На экранах с большим разрешением футер расползается и выглядит не красиво.
![footer](https://user-images.githubusercontent.com/75975369/145666683-5c41a624-ba3c-4b29-a149-88c8e7fd54fb.jpg)
Давай, все же, выставим для футера хеадера и контента некоторое максимальное значение ширины, что бы они выглядели как на макете.
- для узких экранов футер должен быть не таким
![footer2](https://user-images.githubusercontent.com/75975369/145666786-4894222a-d9cf-4050-ae38-e1d2b64c153a.jpg)

**Comment by mglknFSD** [comment]
5. Responsive

- На странице room-details при некоторых разрешениях пропадает паддинг страницы
![room-details](https://user-images.githubusercontent.com/75975369/145666959-edd77b30-eb5e-4c20-a129-2a0eb8d150b1.jpg)

- как я помню, есть требование что бы все элементы были максимально резиновыми, для того что бы они заполняли максимально доступное пространство не оставляя пустот для маскимально широкого спектра дисплеев. Давай исправим виджеты комнаты на странице search-room/filter что бы они были резиновыми. Сейчас у тебя работает вот так.


https://user-images.githubusercontent.com/75975369/145667291-aa20b801-f9d6-4293-b82d-c6a712846ca9.mp4

Давай сделаем что бы это работало так.

https://user-images.githubusercontent.com/75975369/145667351-9d5482c8-8c3d-4ae7-b892-e15d3cf5c48c.mp4

Это нужно для некоторых планшетных разрешений. Например на IPad эта страница выглядит не очень. Сюда бы влезла еще одна колонка с комнатами.

![ipad](https://user-images.githubusercontent.com/75975369/145667456-9ae4bcce-9d67-451b-a91c-48fbb55f6137.jpg)

**Comment by mglknFSD** [comment]
6. Для виджета комнаты хорошо бы добавить анимацию смены картинки.

**Comment by mglknFSD** [comment]
7.Сейчас галлерея у тебя работает так что она прячет части изображений. Давай сделаем так что бы изображения при разных разрешениях сохраняли свои пропрорции.

https://user-images.githubusercontent.com/75975369/145667587-7872216e-4eac-426e-b963-4667b1fc0d86.mp4

**Comment by igor-smolkov** [comment]
> 2. У нас в бест практис есть пункт по поводу того куда должны вести ссылки на сторонние сервисы.

все ссылки в соответствии с HTML 2.11 и HTML 2.12. еще поправлю HTML 2.13
не нашел пункта описывающего ссылки на сторонние сервисы с неопределенным адресом
могу заменить "/mock-address/change-me" на заглавную страницу соответственных сервисов

**Comment by igor-smolkov** [comment]
> 3. Hover эффект в меню влияет на размер элемента и двигает соседей. Такого поведения лучше избегать

согласно макету выделенный пункт меню имеет жирное начертание, при этом ширина самого пункта определяется содержимым, т.е. шириной текста, следовательно при смене начертания текста меняется ширина пункта, из-за чего происходит небольшое смещение остальных пунктов расположенных строчно друг за другом
следует исправить текущее поведение или подумать над другим hover эффектом?
если первый вариант, можно совет на что обратить внимание чтобы это исправить?

**Comment by mglknFSD** [comment]
> > 3\. У нас в бест практис есть пункт по поводу того куда должны вести ссылки на сторонние сервисы.
> 
> все ссылки в соответствии с HTML 2.11 и HTML 2.12. еще поправлю HTML 2.13 не нашел пункта описывающего ссылки на сторонние сервисы с неопределенным адресом могу заменить "/mock-address/change-me" на заглавную страницу соответственных сервисов

Было требование что бы ссылки соцсетей вели на сами соцсети (главные страницы). Возможно это требование убрали.

**Comment by mglknFSD** [comment]
> > 5\. Hover эффект в меню влияет на размер элемента и двигает соседей. Такого поведения лучше избегать
> 
> согласно макету выделенный пункт меню имеет жирное начертание, при этом ширина самого пункта определяется содержимым, т.е. шириной текста, следовательно при смене начертания текста меняется ширина пункта, из-за чего происходит небольшое смещение остальных пунктов расположенных строчно друг за другом следует исправить текущее поведение или подумать над другим hover эффектом? если первый вариант, можно совет на что обратить внимание чтобы это исправить?

Я не очень понял вопрос. Нужно просто что сделать так что бы текст становился жирным, но это не отказывало эффекта на ширину. Вот и все.

**Comment by mglknFSD** [comment]
Отлично! Но есть пара недочетов

1. Y страниц появились границы (у всех страниц) в виде тени. И какие-то серые полосы у галлереи.

![gallery](https://user-images.githubusercontent.com/75975369/146669121-97f5c409-95e0-4fc8-9838-45d2d0547848.jpg)

2. Если нажать на колесико мыши - то проблема остается.

https://user-images.githubusercontent.com/75975369/146669249-caeba23c-4859-4186-8e96-f102c1be5b18.mp4
