### ISSUE TITLE
Организация проекта

### ISSUE THREAD

**Issue by mglknFSD** [igor-smolkov/toxin#30]
1. Папка assets. 
Папки и файлы организуются в соответсвии с семантикой. assets или static или public это папка в которую обычно помещают артефакты которые непосредственно к коду отношения не имеют. Картинки, шрифты, фавинонки и прочее. Стилям, которые ты используешь в своем коде там делать не чего. Ее хранят в корне проета, т е это не исходный код (src -> source). Если бросать все куда попало - будет беспорядок. 

2. В проекте не должно быть ничего лишнего - например лишних шрифтов.

**Comment by igor-smolkov** [comment]
> 2. В проекте не должно быть ничего лишнего - например лишних шрифтов.

из шрифтов есть только: montserrat-regular, montserrat-bold и material-icons-regular, все три используются в проекте
полагаю речь идет о лишних форматах этих шрифтов

**Comment by mglknFSD** [comment]
> > 3\. В проекте не должно быть ничего лишнего - например лишних шрифтов.
> 
> из шрифтов есть только: montserrat-regular, montserrat-bold и material-icons-regular, все три используются в проекте полагаю речь идет о лишних форматах этих шрифтов

Обрати внимания на требования по шрифтам в бест практис, и тебе будет понятно о чем идет речь.

**Comment by mglknFSD** [comment]
Желательно, даже если картинка одна в компоненте, положить ее в папку как вот тут.

![imgs](https://user-images.githubusercontent.com/75975369/146668841-9acadc8d-1062-4f02-b8d5-bf38dbcb0e47.jpg)
