### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [igor-smolkov/toxin#32]
1. Крайне неудачное именование переменных. Что если то, что ты называешь purple дизайнер из фиолетового сделает розовым, тебе придется вводить новую переменную и переименовывать purple в pink по всему проекту. Смысл в этой переменной в таком случае теряется. Именовать переменные нужно по смыслу. Есть главный цвет, есть второстепенный, есть для шрифта, для бэкграунда и т д. Градиенты то же можно поместить в переменную. Плюс не понятно что означает -10per -5per.

![vars](https://user-images.githubusercontent.com/75975369/145669116-0c154404-8824-40c8-a16a-61d5657fa3df.jpg)

**Comment by mglknFSD** [comment]
2. rem or px

Давай выберем что-то одно или rem или px.  Если ты используешь rem то допустимо указывать в px ширину border-а. Для всего остального используй rem.

**Comment by mglknFSD** [comment]
3. keyframes это декларация для анимаций. Они задаются в корне и применяются в конкретных классах
![keyframe](https://user-images.githubusercontent.com/75975369/145670141-235cb597-ea6b-499d-b125-e761694b736b.jpg)
.

**Comment by mglknFSD** [comment]
4. Вот так делать не стоит. SVG должно хранится в виде файла с расширением .svg. И вставляться в нужное место в шаблоне.

![svg](https://user-images.githubusercontent.com/75975369/145670511-cf0d87d6-0cf0-47e1-95a1-f894431500fa.jpg)

**Comment by igor-smolkov** [comment]
> 3. keyframes это декларация для анимаций. Они задаются в корне и применяются в конкретных классах

понял так: все анимации в отдельном файле scss, в корне (src)
а вот про применение не очень понял, импортируем этот файл и используем анимацию по имени, как прежде или нужно как-то иначе делать? можно подробнее

**Comment by igor-smolkov** [comment]
> 4. Вот так делать не стоит. SVG должно хранится в виде файла с расширением .svg. И вставляться в нужное место в шаблоне.

все svg я вынесу, но вставка в шаблоне полагаю нужна только для контентных изображений (вроде лого в примере), остальные останутся в css url

**Comment by mglknFSD** [comment]
> > 5\. keyframes это декларация для анимаций. Они задаются в корне и применяются в конкретных классах
> 
> понял так: все анимации в отдельном файле scss, в корне (src) а вот про применение не очень понял, импортируем этот файл и используем анимацию по имени, как прежде или нужно как-то иначе делать? можно подробнее

В корне файла где они используются.

**Comment by mglknFSD** [comment]
> > 7\. Вот так делать не стоит. SVG должно хранится в виде файла с расширением .svg. И вставляться в нужное место в шаблоне.
> 
> все svg я вынесу, но вставка в шаблоне полагаю нужна только для контентных изображений (вроде лого в примере), остальные останутся в css url

Все svg надо вынести как svg файлы. Это нужно для удобства замены. Если картинка поменяется, нужно иметь возможность заметить ее как картинку, а не как код. К слову все картинки носящие декоративный характер (т е которые не подразумевается что будут динамически прилетать с сервера), мы храним в компонентах.

**Comment by mglknFSD** [comment]
БЭМ. Вложеные блоки не допустимы. Нужно иметь плоскую структуру блоков.

![nested block](https://user-images.githubusercontent.com/75975369/146668599-7e022e4f-03d0-45cb-b1dd-a7f81a65c1aa.jpg)
