### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [igor-smolkov/toxin#34]
Зачем тут такой дефолтный параметр? Какую проблему он решает?

![default](https://user-images.githubusercontent.com/75975369/146669364-fe798466-7242-4e54-a75e-95a2d5b12e0a.jpg)

**Comment by mglknFSD** [comment]
Пустой тег
![empty tag](https://user-images.githubusercontent.com/75975369/146669412-334f966b-9ba3-4251-a797-47f0974f4d53.jpg)

**Comment by mglknFSD** [comment]
Поработай над семантикой тегов. Очень много дивов и спанов.

**Comment by igor-smolkov** [comment]
> Зачем тут такой дефолтный параметр? Какую проблему он решает?
> 
> ![default](https://user-images.githubusercontent.com/75975369/146669364-fe798466-7242-4e54-a75e-95a2d5b12e0a.jpg)

в данном случае, если убрать пустой объект, то будет ошибка деструктуризаци неопределенного параметра, при использовании компонента без опций

- возможность отрисовки компонента без определения его опций

`+calendar` - отрисует календарь по-умолчанию, текущий месяц без выбранных дат
в обратном случае, необходимо всегда передавать объект опций при использовании компонента

- возможность расширять компоненты, которые прежде использовались без опций, не меняя места кода, где эти компоненты включаются

многим структурным компонентам, например, не нужны опции
при таком подходе использование компонентов становится единообразным, опции передаются только там где они нужны

**Comment by mglknFSD** [comment]
> > Зачем тут такой дефолтный параметр? Какую проблему он решает?
> > ![default](https://user-images.githubusercontent.com/75975369/146669364-fe798466-7242-4e54-a75e-95a2d5b12e0a.jpg)
> 
> в данном случае, если убрать пустой объект, то будет ошибка деструктуризаци неопределенного параметра, при использовании компонента без опций
> 
> * возможность отрисовки компонента без определения его опций
> 
> `+calendar` - отрисует календарь по-умолчанию, текущий месяц без выбранных дат в обратном случае, необходимо всегда передавать объект опций при использовании компонента
> 
> * возможность расширять компоненты, которые прежде использовались без опций, не меняя места кода, где эти компоненты включаются
> 
> многим структурным компонентам, например, не нужны опции при таком подходе использование компонентов становится единообразным, опции передаются только там где они нужны

Ok
