### ISSUE TITLE
Мелкие правки по html css

### ISSUE THREAD

**Issue by Geksanit** [igor-smolkov/toxin#41]
1 Не все иконки в <img
![i](https://user-images.githubusercontent.com/31949379/155998432-e1ee20db-2728-422c-b210-abbd954b4c46.png)

2 Определить позицию элемента можно псевдоклассами в css `:first-child` `:not(:last-child)` и т.д.
![image](https://user-images.githubusercontent.com/31949379/155997507-628da0b7-7992-46f7-9917-525de12acdbf.png)

**Comment by igor-smolkov** [comment]
> 1 Не все иконки в <img
  
Это шрифт material-icons  
Предлагаешь, в данном случае, как-то заменить `<i class="extra-list__icon">location_city</i>` на `<img />`?  
Не очень понятно как, но из того что находил, [не рекомендуют](https://stackoverflow.com/questions/60005658/how-to-use-google-material-design-icons-for-html-image-control-instead-of-image) использовать с `<img>`, рекомендуют с `<i>` или [`<span>`](https://google.github.io/material-design-icons/).
Или использовать картинки из поддиректорий `/img` вместо material-icons?
  
> 2 Определить позицию элемента можно псевдоклассами в css :first-child :not(:last-child) и т.д.
  
Использование комбинированных селекторов не рекомендуется в [БЭМ](https://ru.bem.info/methodology/css/#%D0%BA%D0%BE%D0%BC%D0%B1%D0%B8%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B)  
В методологии не отмечены псевдоклассы, но они имеют тот же вес, что и классы, поэтому старался свети их использование к минимуму  
Нужно заменить все модификаторы позиции на селекторы?

**Comment by Geksanit** [comment]
> Это шрифт material-icons

О, не заметил, тогда норм, оставь.

> Использование комбинированных селекторов не рекомендуется в БЭМ

С другой стороны загромождать код модификаторами по таким мелочам тоже не хорошо. И модификатор не переиспользуется.
Наверно это уже дело привычки. В Конце концов на контейнер можно повесить
```
{
    display: grid;
    gap: 10px;
}
```
На твое усмотрение, тоже можно оставить.
